version : 2

sources:
  - name: hr
    database: sources
    schema: hr
    
    tables: 
     - name: src_employees
     - name: src_departments
     - name: src_countries
     - name: src_salary
     - name: src_locations
     - name: src_regions
     - name: src_jobs